#!/bin/bash

export CLASSPATH=$CLASSPATH:/usr/share/openjfx/lib
export VISUAL=/usr/bin/nvim

PATH=$PATH:/home/$USER/Documents/Application/energia-1.8.10E23
PATH=$PATH:/home/$USER/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin
PATH=$PATH:/home/$USER/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin
PATH=$PATH:/home/$USER/Documents/Application/blender-2.82a-linux64/
PATH=$PATH:/home/$USER/Documents/Application/arduino-1.8.12/
PATH=$PATH:/home/$USER/Documents/Application/flutter/bin/
PATH=$PATH:/home/$USER/.arduino15/packages/esp32/tools/esptool_py/2.6.1/
PATH=$PATH:/home/$USER/arduino-cli/bin/
PATH=$PATH:/home/$USER/Documents/Application/energia-1.8.10E23
PATH=$PATH:/home/$USER/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin
PATH=$PATH:/home/$USER/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin
PATH=$PATH:/home/$USER/Documents/Application/blender-2.82a-linux64/
PATH=$PATH:/home/$USER/Documents/Application/arduino-cli/
PATH=$PATH:$GOPATH
PATH=$PATH:$GOROOT/bin
PATH=$PATH:$HOME/.cargo/bin/
ANDROID_SDK_ROOT=/home/$USER/Android/Sdk
PI3_IP=''
PI3_ADDR="http://$PI3_IP"

PICO_SDK_PATH=/home/$USER/Documents/C/pico/pico-sdk/
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

PI4_IP=''
PI4_ADDR="http://$PI4_IP"

export EDITOR=nvim
if command -v dircolors >/dev/null
then
  eval `dircolors /home/$USER/.dir_colors/dircolors`
fi
